# Generated by Django 5.2 on 2025-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=5)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
