# Generated by Django 5.2 on 2025-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_partrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Awaiting Delivery', 'Awaiting Delivery')], default='Pending', max_length=20),
        ),
    ]
