# Generated by Django 5.2 on 2025-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_partrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partrequest',
            name='approved',
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Approved - Awaiting Delivery', 'Approved - Awaiting Delivery'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=30),
        ),
    ]
